on:
  push:
  schedule:
    - cron: "0 0 * * *"
name: update-pkg

jobs:
  update-pkg:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2

      - name: Install R package linux dependencies
        run: |
          sudo apt update
          sudo apt-get install libcurl4-openssl-dev libnetcdf-dev libudunits2-dev libgdal-dev libharfbuzz-dev libfribidi-dev
        shell: bash

      - name: Install R packages
        run: Rscript -e 'install.packages(c("devtools", "dplyr", "here", "httr", "jsonlite", "magrittr", "stringr", "usethis"))'

      - name: Update R pkg
        run: Rscript -e 'here::here("data-raw/dnld_get_boem_weas.R") |> source()'

      - name: Set up Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
      - name: Commit all changes
        run: |
          git add -A && git commit -m 'Build site' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
